### ISSUE TITLE
Installation Failure (Unity 2021.3.9.f1)

### ISSUE THREAD

**Issue by 21022079-Chong-Ding-Zhang** [axoverse/xworld_amb#5]
- Tried constantly refreshing download but to no avail,
- Restarted Unity Hub but still the same error. 

![image](https://user-images.githubusercontent.com/106566645/235858064-a2eb446f-7384-459b-86f7-472dc27850c1.png)

**Comment by seghcder** [comment]
Seems some others have reported this - https://www.reddit.com/r/Unity3D/comments/zt2unx/install_failed_installation_failed/

- Check disk space?
- Check the Unity Hub log files? (bottom of page) https://docs.unity3d.com/Manual/LogFiles.html
- Try running hub as administrator? 


If all else fails, then try installing Visual Studio Community 2022 - 
https://visualstudio.microsoft.com/vs/community/
Then configure - 
https://learn.microsoft.com/en-us/visualstudio/gamedev/unity/get-started/getting-started-with-visual-studio-tools-for-unity?pivots=windows

Then install Unity via the downloadable installer - https://download.unity3d.com/download_unity/ad3870b89536/UnityDownloadAssistant-2021.3.9f1.exe

**Comment by 21022079-Chong-Ding-Zhang** [comment]
- **Unity Hub Log File:** [log.txt](https://github.com/axoverse/xworld_amb/files/11439182/log.txt)
- **Using 2021.3.9f1 Download Assistant** 
![image](https://github.com/axoverse/xworld_amb/assets/106566645/02134e6b-e81b-4f54-ae36-096b4a5210b2)
_(steps were done after reboot)_

**Comment by 21022079-Chong-Ding-Zhang** [comment]
**After running as Administrator:**
- ![image](https://github.com/axoverse/xworld_amb/assets/106566645/5a9c4202-e3ac-42b4-9a75-cdf8deac02a2) _(Selected Ignore option)_
- ![image](https://github.com/axoverse/xworld_amb/assets/106566645/d965a46b-1dc9-4a0e-aefb-4dd7d08c9c79)


**New project**
- ![image](https://github.com/axoverse/xworld_amb/assets/106566645/5a9c4202-e3ac-42b4-9a75-cdf8deac02a2) _(Selected Ignore option)_
- ![image](https://github.com/axoverse/xworld_amb/assets/106566645/c9bce23e-2267-404c-9461-1857f0f2295e)

**Comment by seghcder** [comment]
ok - you'll need to try some of the other options. 

https://forum.unity.com/threads/unity-2021-1-6f1-files-missing-on-clean-install.1107110/

Do you have an overly assertive antivirus thats removing files? Try reverting to Defender.

Another option would be to install HyperV or VirtualBox and try doing a clean OS install then Unity install. If you are familiar with Linux then use that OS to avoid OS licensing issues. Choose a variant supported by Unity.

**Comment by 21022079-Chong-Ding-Zhang** [comment]
Still facing the same compiler error, (not sure if this helps but) here's a screenshot of when I'm opening git bash
![image](https://github.com/axoverse/xworld_amb/assets/106566645/b8a84c1b-807c-4d7c-9558-db268899a21b)

**Comment by seghcder** [comment]
it doesnt seem related. Did you get a chance to try/consider some of the other options mentioned here?

https://github.com/axoverse/xworld_amb/issues/5#issuecomment-1544801484

Otherwise, it might be something that RP tech support might need to address sorry!
