### ISSUE TITLE
Type or namespace name 'RoutingWayPoint'

### ISSUE THREAD

**Issue by 21005042-Toh-Jun-Cheng** [axoverse/xworld_amb#7]
![image](https://github.com/axoverse/xworld_amb/assets/106566151/577fd890-4ae6-49fe-bead-3e0cd2a78220)

Error pops up when I copied the code from XwNavAgent script to my own script.

![image](https://github.com/axoverse/xworld_amb/assets/106566151/7e3e3fae-fbde-4a40-a958-1f3b4522bd1d)
I noticed if I removed "UnityEngine.AI" the same issue pops up, but the issue does not surface in XwNavAgent.

**Comment by seghcder** [comment]
@surfacedfox can you help @21005042-Toh-Jun-Cheng  with this issue? I believe its an assembly definition issue. Check which assembly the Routing waypoint is in and add it to the asmdef for their scripts directory. If needed, set up a teams call.

**Comment by seghcder** [comment]
@21005042-Toh-Jun-Cheng this worked for me...  did you also have the using reference? I didnt add the asmdef either.

```C#
using System.Collections;
using System.Collections.Generic;
using Axomem.XWorld;
using UnityEngine;

public class Test : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        var o = FindObjectOfType<RoutingWaypoint>();
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
```

**Comment by surfacedfox** [comment]
I'm on this!

**Comment by 21005042-Toh-Jun-Cheng** [comment]
![image](https://github.com/axoverse/xworld_amb/assets/106566151/9f23bbcd-5fb8-4578-8739-c2a4843b20fe)

I have added this using reference and the issue is gone. Thank you.
