### ISSUE TITLE
Cleaner issue & other bugs

### ISSUE THREAD

**Issue by 21022079-Chong-Ding-Zhang** [axoverse/xworld_amb#8]
Here's the progress for the cleaner's interaction so far. I'll describe some basic issues here but hopefully, we can set up a meeting sometime soon.

- The cleaner doesn't exactly clean the surface like how the infected patient infects the surface
- Pathline turns red although the cleaner has immunity (only happens when the cleaner comes into direct contact with the infected patient)
- Occasionally, the program goes completely haywire where the agents start crashing into walls or moving at higher speeds than normal

**Link:** https://youtu.be/cr1q3NQWX-4
_p.s. This video only captures the most ideal version of the simulation running._

**Comment by seghcder** [comment]
It looks like @surfacedfox has had a computer crash and can't help for now (unless he can guide from teams on his phone connected to a screen?) ... Are you able to work with your classmates to help debug bullets one and two? For the third, let us know if it seems CPU related or another issue - ie how frequently it happens and any thoughts on triggers?

**Comment by 21022079-Chong-Ding-Zhang** [comment]
The cleaner issue is resolved! However, the issue of the program going haywire still occurs once in a blue moon and there are still one or two small bugs.
**Link:** https://youtu.be/lkNHRAy4-X8

**Comment by seghcder** [comment]
Looks great @21022079-Chong-Ding-Zhang ! For the haywire issue, one thing you can do is put in some logging now that might help identify and/or isolate when it happens. Also open a new issue in your own repo to capture some data about when it does happen to try to narrow down causes.
